### ISSUE TITLE
在Linux系统下，打开任何md文件，总是显示的文件模版！

### ISSUE THREAD

**Issue by bugs1111** [zhiyelee/mdserver#21]
下载解压完后，执行
~~~
node index
~~~

在mac完全正常。

但在linux下，点击任何`md`文件，浏览器就总是显示`/home/user/mdserver/public/fileTpl.html`。

请问怎么解决呢？@zhiyelee

> linux是ubuntu 16.04 LTS
> node是6.10.3

**Comment by RB-Lab** [comment]
If I understand correctly what this issue is about, here is a fix: #22 @zhiyelee

**Comment by RB-Lab** [comment]
And the workaround is to set `--ftpl ./node_modules/mdserver/public/filetpl.html`

**Comment by zhiyelee** [comment]
v2.2.6 is released.  Thanks  @RB-Lab @bugs1111
